### ISSUE TITLE
Is this compatible with your EFI?

### ISSUE THREAD

**Issue by SurfinDuck69** [danikpanik/XPS-13-9360-Monterey-Hackintosh#2]
https://www.ebay.de/itm/394278640296?mkcid=16&mkevt=1&mkrid=707-127634-2357-0&ssspo=o7_ym3ibqlq&sssrc=2047675&ssuid=rqykxp_tsym&widget_ver=artemis&media=COPY

**Comment by danikpanik** [comment]
> https://www.ebay.de/itm/394278640296?mkcid=16&mkevt=1&mkrid=707-127634-2357-0&ssspo=o7_ym3ibqlq&sssrc=2047675&ssuid=rqykxp_tsym&widget_ver=artemis&media=COPY

Yes, that's the exact card I'm running.
